# Generated by Django 4.2.4 on 2023-08-11 06:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('treemenu', '0002_alter_scheme_options_scheme_chapter_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='scheme',
            name='quantity',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
    ]
